name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (patch, minor, or major)'
        required: false
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint --strict

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: ios

      - name: Typecheck files
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: yarn test --maxWorkers=2 --coverage

  build-release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare

      - name: Set NPM token & GitHub config
        run: |
          npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
          git config user.name "Kuatsu CI/CD"
          git config user.email "null@kuatsu.de"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Validate release type
        if: ${{ inputs.release_type != '' }}
        run: |
          if [[ "${{ inputs.release_type }}" != "patch" && "${{ inputs.release_type }}" != "minor" && "${{ inputs.release_type }}" != "major" ]]; then
            echo "Invalid release type. Must be 'patch', 'minor', or 'major'."
            exit 1
          fi

      - name: Release
        run: |
          if [ -n "${{ inputs.release_type }}" ]; then
            yarn release --release-as ${{ inputs.release_type }}
          else
            yarn release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.CICD_PAT }}
